### ISSUE TITLE
A question about obstacle avoidance

### ISSUE THREAD

**Issue by LiJiangnanBit** [alexliniger/MPCC#31]
Hi, Alex
I have 2 questions:
1. In the track constraints of the MPCC problem quadratic approximation:
![image](https://user-images.githubusercontent.com/23288471/74079226-5b313c00-4a6f-11ea-8ba5-c86ec687feae.png) 
for any k, the track boundary (corridor) is computed according to the **theta** of the corresponding initial guess point. But obviously, the solution might be different from the initial guess, so at the kth point of the solution, the **theta** changes, thus the track boundary is actually not the value used in our constraints. 
So it seems that even when the track constraints are satisfied, the predicted trajectory may have collision with obstacles? How do you deal with this situation?
2. In obstacle avoidance, the vehicle is treated as a point without considering its heading. Does this matter when the corridor becomes narrow? Sometimes even if the point stays within the corridor, part of the vehicle might be out of the corridor because of its length and heading.
Thanks!

**Comment by alexliniger** [comment]
1. Since the track constraints are approximated at each step in the SQP scheme, if the SQP converges, the track constraints are fulfilled. But if you stop early (as we do here) you could be right, it very much depends on how good a linear approximation works for your actual constraints. 

2. To deal with this at the moment I use a safety margin. The issue is that the safety margin makes the problem conservative. So there is a certain trade-off. It would be interesting to implement orientation dependent constraints, but I did not yet found the time to do it.

**Comment by LiJiangnanBit** [comment]
Thanks for your answer :smile:
