### ISSUE TITLE
make failed

### ISSUE THREAD

**Issue by buchiyangcong** [alexliniger/MPCC#43]
When i tried make the project of C++ version,  an error occurred.  but ./MPCC operated normal.

The error message was mainly about " ~./config.h:24:10: fatal error: Eigen/Dense: No such file or directory
 #include <Eigen/Dense> compilation terminated.CMakeFiles/MPCC.dir/build.make:62: recipe for target
'CMakeFiles/MPCC.dir/main.cpp.o' failed " . 

I want to know if this status was properly. Anyone could help me?  Thank you very much.

**Comment by alexliniger** [comment]
Hi I tested the master branch, and reinstalled everything with the install.sh script and compiled it from scratch.
I did not have any issues and everything worked smoothly. 
From you error message, I assume the issue is related to not correctly installing Eigen. If you did not install eigen with the install.sh script you may need to change the inlcude path.
Best,
Alex
