### ISSUE TITLE
HpipmIterface::setSoftConstraints

### ISSUE THREAD

**Issue by DreamonZhu** [alexliniger/MPCC#49]
Hi,
https://github.com/alexliniger/MPCC/blob/3ec7805e7a176c57250c1a414a6d2b871e472d74/C%2B%2B/Interfaces/hpipm_interface.cpp#L182
why don't we just push index j into idx_s but have j plus nbu[i] and nbx[i]?

**Comment by alexliniger** [comment]
because this is the index of the constraint and by the implementation of hpipm are the indexes of the soft constraints first states then inputs then polytopic constraints.
So index 0 would correspond to have a soft constraint on the bound of the first state. I hope this makes sense otherwise you need to read the hpipm documentation
