### ISSUE TITLE
Optimal Cost at Each time step .

### ISSUE THREAD

**Issue by prajwalthakur** [alexliniger/MPCC#92]
Hi, I have some questions about the optimal optimization cost. 
1. At each time step, we are solving some fixed number of sqp problems through MPC
2. The line below returns the optimal solution for each MPC iteration https://github.com/alexliniger/MPCC/blob/bd331621ba47ae3326711922a863bdb1cdf2d2ea/C%2B%2B/Interfaces/hpipm_interface.cpp#L376
3. How should I get the total optimal cost over the whole track?  (suppose the number of Sqp steps=1, then the total optimal cost is the summation of ( optimal cost we get at each MPC iteration ).  my question is what the optimal cost after each MPC iteration should it be 
0.5( X.TQX + 2*q.TX + U.TRU) at index = 0 ? where X ,Q,q,U,R as defined in  hpipminteface::solve function, or should it be something else?
4. I used the above formula to get the optimal cost after each iteration,  and when plotting the cost vs time, I observed that sometimes I am getting negative and sometimes +ve values of optimal cost and thus observing the same behavior in average cost ); I believe the negative cost is due to the q.TX part?
5.  I am tuning the weights of mpcc and trying to analyze which one is best from the total cost over the track. (in general, I look for the lowest cost  and variance ) But it might not be the case; for example, I am attaching a figure below. different cases represent different sets of weights for mpc
![optimal_cost_box_plot_comp](https://github.com/alexliniger/MPCC/assets/42039745/60595371-1142-47a0-9238-47416d2298ce)

**Comment by alexliniger** [comment]
The issue when computing the optimal cost for the whole track is that you want to compute the cost of the closed loop system, however you try to compute the open loop MPC cost, the two are not really related.

I would do it differently, I would suggest you just define some metrics that interest you, this could be lap time or something similar. If you really want to compute the closed loop cost, you can take the closed loop trajectory and compute the cost using its nonlinear form. However, in the case of MPCC this is a bit tricky due to the "virtual" states.
